# Generated by Django 5.2.6 on 2025-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern Professional'), ('classic', 'Classic Traditional'), ('creative', 'Creative Designer'), ('minimal', 'Minimal Clean'), ('executive', 'Executive Professional'), ('tech', 'Tech Developer'), ('corporate', 'Corporate Business'), ('bold', 'Bold Modern'), ('elegant', 'Elegant Classic'), ('gradient', 'Gradient Creative'), ('compact', 'Compact Professional'), ('colorful', 'Colorful Vibrant'), ('academic', 'Academic Research'), ('startup', 'Startup Innovator'), ('medical', 'Medical Healthcare')], default='modern', max_length=50),
        ),
    ]
