# Generated by Django 5.2.6 on 2025-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern Professional'), ('classic', 'Classic Traditional'), ('creative', 'Creative Designer'), ('minimal', 'Minimal Clean'), ('executive', 'Executive Professional'), ('tech', 'Tech Developer'), ('bold', 'Bold Modern'), ('corporate', 'Corporate Blue'), ('elegant', 'Elegant Serif'), ('gradient', 'Gradient Creative'), ('compact', 'Compact Professional'), ('colorful', 'Colorful Modern')], default='modern', max_length=50),
        ),
    ]
