# Generated by Django 5.2.6 on 2025-11-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('professional', 'Professional'), ('creative', 'Creative'), ('minimal', 'Minimal')], default='professional', max_length=50),
        ),
    ]
